<script setup lang="ts">
import{computed,onMounted,ref}from'vue';import{api}from'../api/client'
const items=ref<any[]>([]),loading=ref(false),showModal=ref(false),error=ref(''),keyword=ref(''),statusFilter=ref('')
const form=ref({building:'',room:'',status:'available',available_from:''})
const filtered=computed(()=>items.value.filter(x=>(!statusFilter.value||x.Status===statusFilter.value)&&(!keyword.value||`${x.Building}${x.Room}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const counts=computed(()=>({total:items.value.length,available:items.value.filter(x=>x.Status==='available').length,occupied:items.value.filter(x=>x.Status==='occupied').length,maintenance:items.value.filter(x=>x.Status==='maintenance').length}))
async function load(){loading.value=true;try{items.value=(await api.get('/properties',{params:{page:1,page_size:100}})).data.items||[]}finally{loading.value=false}}
async function add(){error.value='';try{await api.post('/properties',form.value);showModal.value=false;form.value={building:'',room:'',status:'available',available_from:''};await load()}catch(e:any){error.value=e.response?.data?.error?.message||'新增房源失败'}}
async function changeStatus(id:string,status:string){await api.patch(`/properties/${id}/status`,{status});await load()}
function statusText(v:string){return({available:'可租',occupied:'已出租',maintenance:'维修中'} as any)[v]||v}
onMounted(load)
</script><template><div class="page"><div class="page-title"><div><h1>房源单元</h1><p>维护楼栋、房间、当前状态和可租信息</p></div><button class="primary-button" @click="showModal=true">＋ 新增房源</button></div><div class="stat-grid"><div class="stat-card"><span>全部房源</span><strong>{{counts.total}}</strong></div><div class="stat-card"><span>当前可租</span><strong>{{counts.available}}</strong></div><div class="stat-card"><span>已出租</span><strong>{{counts.occupied}}</strong></div><div class="stat-card"><span>维修中</span><strong>{{counts.maintenance}}</strong></div></div><section class="card"><div class="toolbar"><div class="toolbar-left"><div class="field"><input class="search-input" v-model="keyword" placeholder="搜索楼栋或房间"></div><div class="field"><select v-model="statusFilter"><option value="">全部状态</option><option value="available">可租</option><option value="occupied">已出租</option><option value="maintenance">维修中</option></select></div></div><button class="secondary-button" @click="load">刷新数据</button></div><table v-if="filtered.length" class="data-table"><thead><tr><th>房源编号</th><th>楼栋</th><th>房间</th><th>可租日期</th><th>当前状态</th><th>快捷操作</th></tr></thead><tbody><tr v-for="x in filtered" :key="x.ID"><td><code>{{x.ID.slice(0,8)}}</code></td><td><strong>{{x.Building}}</strong></td><td>{{x.Room}}</td><td>{{String(x.AvailableFrom).slice(0,10)}}</td><td><span class="status-badge" :class="x.Status">{{statusText(x.Status)}}</span></td><td><div class="action-group"><button class="secondary-button" @click="changeStatus(x.ID,'available')">设为可租</button><button class="secondary-button" @click="changeStatus(x.ID,'occupied')">设为出租</button><button class="danger-button" @click="changeStatus(x.ID,'maintenance')">报修</button></div></td></tr></tbody></table><div v-else class="empty-state"><b>{{loading?'正在加载房源...':'暂无符合条件的房源'}}</b><span>点击右上角“新增房源”开始录入</span></div></section><div v-if="showModal" class="modal-mask" @click.self="showModal=false"><div class="modal"><div class="modal-header"><div><h3>新增房源</h3><small>录入房源基础信息，创建后可继续绑定设施</small></div><button class="close-button" @click="showModal=false">×</button></div><div class="modal-body"><div class="form-grid"><label><span>楼栋名称 *</span><input v-model="form.building" placeholder="例如：一期 A 座"></label><label><span>房间号 *</span><input v-model="form.room" placeholder="例如：101"></label><label><span>初始状态</span><select v-model="form.status"><option value="available">可租</option><option value="maintenance">维修中</option></select></label><label><span>可租日期</span><input v-model="form.available_from" type="date"></label></div><p v-if="error" class="form-error">{{error}}</p></div><div class="modal-footer"><button class="secondary-button" @click="showModal=false">取消</button><button class="primary-button" :disabled="!form.building||!form.room" @click="add">确认新增</button></div></div></div></div></template>