ALTER TABLE deposit_ledgers ADD COLUMN reason VARCHAR(255) NOT NULL DEFAULT '', ADD COLUMN actor_id CHAR(36) NULL;
ALTER TABLE lease_versions ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
