#!/usr/bin/env bash
set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../..";BUG_ID=BUG-030;source scripts/verify/testlib.sh;login_admin
admin=$(sql "SELECT id FROM users WHERE username='admin';")
x=$(new_id);x=${x:0:8};p=$(new_id);op=$(new_id);t=$(new_id);l=$(new_id);ol=$(new_id);plan=$(new_id);oplan=$(new_id);wi=$(new_id);si=$(new_id);run=$(new_id);item=$(new_id);start=2027-08-01;end=2027-09-01;due=2027-08-06;amount=170000
sql_exec "INSERT INTO properties(id,building,room,status,available_from) VALUES('$p','BUG030-$x','A-01','occupied','2027-01-01'),('$op','BUG030-$x','B-01','occupied','2027-01-01');INSERT INTO tenants(id,name,phone,email,identity_no,status) VALUES('$t','BUG030 tenant','','','','active');INSERT INTO leases(id,property_id,tenant_id,status,start_date,end_date,monthly_rent,deposit) VALUES('$l','$p','$t','active','2027-01-01','2028-12-31',150000,300000),('$ol','$op','$t','active','2027-01-01','2028-12-31',99000,198000);INSERT INTO billing_plans(id,lease_id,status,billing_day,due_days,advance_days,next_period_start) VALUES('$plan','$l','active',1,5,7,'$start'),('$oplan','$ol','active',1,5,7,'2027-10-01');INSERT INTO billing_plan_items(id,plan_id,kind,name,amount,enabled) VALUES('$wi','$plan','water','Water fee',12000,TRUE),('$si','$plan','service','Service fee',8000,TRUE);INSERT INTO billing_runs(id,trigger_type,period_key,status,actor_id,total,succeeded,failed,started_at,finished_at) VALUES('$run','manual','BUG030-$x','completed_with_errors','$admin',1,0,1,UTC_TIMESTAMP(),UTC_TIMESTAMP());INSERT INTO billing_run_items(id,run_id,plan_id,lease_id,bill_id,period_start,period_end,due_date,amount,status,error_message,attempts) VALUES('$item','$run','$plan','$l',NULL,'$start','$end','$due',$amount,'failed','simulated transient failure',1);"
request POST "/api/billing-runs/$run/items/$item/retry";first=$HTTP_STATUS
state=$(sql "SELECT CONCAT(status,'|',attempts,'|',COALESCE(bill_id,''),'|',period_start,'|',period_end,'|',due_date,'|',amount) FROM billing_run_items WHERE id='$item';");bill=$(sql "SELECT CONCAT(COUNT(*),'|',COALESCE(MIN(period_start),''),'|',COALESCE(MIN(period_end),''),'|',COALESCE(MIN(due_date),''),'|',COALESCE(MIN(amount),0),'|',COALESCE(MIN(status),'')) FROM bills WHERE lease_id='$l';");parts=$(sql "SELECT CONCAT(COUNT(*),'|',COALESCE(SUM(amount),0),'|',COALESCE(SUM(kind='rent'),0),'|',COALESCE(SUM(kind='water'),0),'|',COALESCE(SUM(kind='service'),0)) FROM bill_items WHERE bill_id=(SELECT bill_id FROM billing_run_items WHERE id='$item');");billid=$(sql "SELECT bill_id FROM billing_run_items WHERE id='$item';");key=$(sql "SELECT COUNT(*) FROM idempotency_keys WHERE scope='billing.plan' AND request_key='$plan:$start' AND resource_id='$billid';");next=$(sql "SELECT next_period_start FROM billing_plans WHERE id='$plan';");other=$(sql "SELECT next_period_start FROM billing_plans WHERE id='$oplan';");audit=$(sql "SELECT COUNT(*) FROM audit_logs WHERE action='billing_run.retry' AND resource='billing_run_item' AND resource_id='$item' AND actor_id='$admin';")
request POST "/api/billing-runs/$run/items/$item/retry";second=$HTTP_STATUS;bill_count=$(sql "SELECT COUNT(*) FROM bills WHERE lease_id='$l';");key_count=$(sql "SELECT COUNT(*) FROM idempotency_keys WHERE scope='billing.plan' AND request_key='$plan:$start';");attempts=$(sql "SELECT attempts FROM billing_run_items WHERE id='$item';");audit2=$(sql "SELECT COUNT(*) FROM audit_logs WHERE action='billing_run.retry' AND resource='billing_run_item' AND resource_id='$item' AND actor_id='$admin';")
[[ $first == 200 ]]||fail "failed retry expected HTTP 200 got $first body=$HTTP_BODY"
[[ $state == "succeeded|2|$billid|$start|$end|$due|$amount" ]]||fail "retried item state mismatch got $state"
[[ $bill == "1|$start|$end|$due|$amount|unpaid" ]]||fail "retry created wrong bill period got $bill"
[[ $parts == "3|$amount|1|1|1" ]]||fail "retry bill items mismatch got $parts"
[[ $key == 1 ]]||fail "failed-period idempotency key missing or not linked got $key"
[[ $next == 2027-09-01 ]]||fail "target plan expected 2027-09-01 got $next"
[[ $other == 2027-10-01 ]]||fail "unrelated plan changed got $other"
[[ $audit == 1 ]]||fail "successful retry expected one audit row got $audit"
[[ $second == 409 && $bill_count == 1 && $key_count == 1 && $attempts == 2 && $audit2 == 1 ]]||fail "rejected second retry changed state status=$second bills=$bill_count keys=$key_count attempts=$attempts audits=$audit2"
finish 10
